spring:
  profiles:
    active:
      dev
  application:
    name:
      skiskii-backend-service
  mvc:
    pathmatch:
      matching-strategy:
        ANT_PATH_MATCHER

server:
  servlet:
    context-path:
      /skiskii
